# CMake generated Testfile for 
# Source directory: /home/yjj/cgal_halfspace_project
# Build directory: /home/yjj/cgal_halfspace_project/build-absl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(halfspace_smooth_tree "/home/yjj/cgal_halfspace_project/build-absl/halfspace_smooth_tree_test")
set_tests_properties(halfspace_smooth_tree PROPERTIES  _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;70;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(spherical_robot_model "/home/yjj/cgal_halfspace_project/build-absl/spherical_robot_model_test" "/home/yjj/cgal_halfspace_project/tests/data/spherical_robot_test.urdf" "/home/yjj/cgal_halfspace_project/resources/vamp/panda/panda_spherized.urdf")
set_tests_properties(spherical_robot_model PROPERTIES  _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;74;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_smooth_distance "/home/yjj/cgal_halfspace_project/build-absl/boundary_smooth_distance_test")
set_tests_properties(boundary_smooth_distance PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;80;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(halfspace_compiled_tree "/home/yjj/cgal_halfspace_project/build-absl/halfspace_compiled_tree_test")
set_tests_properties(halfspace_compiled_tree PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;86;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_direct_tree "/home/yjj/cgal_halfspace_project/build-absl/boundary_direct_tree_test")
set_tests_properties(boundary_direct_tree PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;91;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(incremental_boundary_direct_tree "/home/yjj/cgal_halfspace_project/build-absl/incremental_boundary_direct_tree_test")
set_tests_properties(incremental_boundary_direct_tree PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;96;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_direct_frame_cache "/home/yjj/cgal_halfspace_project/build-absl/boundary_direct_frame_cache_test")
set_tests_properties(boundary_direct_frame_cache PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;104;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(sparse_voxel_occupancy "/home/yjj/cgal_halfspace_project/build-absl/sparse_voxel_occupancy_test")
set_tests_properties(sparse_voxel_occupancy PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;109;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_local_tree "/home/yjj/cgal_halfspace_project/build-absl/boundary_local_tree_test")
set_tests_properties(boundary_local_tree PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;114;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_boundary_tree "/home/yjj/cgal_halfspace_project/build-absl/octree_boundary_tree_test")
set_tests_properties(octree_boundary_tree PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;119;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_convex_approximation "/home/yjj/cgal_halfspace_project/build-absl/octree_convex_approximation_test")
set_tests_properties(octree_convex_approximation PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;124;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(conservative_voxelization "/home/yjj/cgal_halfspace_project/build-absl/conservative_voxelization_test")
set_tests_properties(conservative_voxelization PROPERTIES  _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;128;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_occupancy "/home/yjj/cgal_halfspace_project/build-absl/octree_occupancy_test")
set_tests_properties(octree_occupancy PROPERTIES  _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;132;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_pruning "/home/yjj/cgal_halfspace_project/build-absl/octree_pruning_test")
set_tests_properties(octree_pruning PROPERTIES  _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;136;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_rectangular_pruning "/home/yjj/cgal_halfspace_project/build-absl/octree_rectangular_pruning_test")
set_tests_properties(octree_rectangular_pruning PROPERTIES  _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;140;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_boundary "/home/yjj/cgal_halfspace_project/build-absl/octree_boundary_test")
set_tests_properties(octree_boundary PROPERTIES  _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;144;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(incremental_voxel_boundary "/home/yjj/cgal_halfspace_project/build-absl/incremental_voxel_boundary_test")
set_tests_properties(incremental_voxel_boundary PROPERTIES  _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;148;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_frontend "/home/yjj/cgal_halfspace_project/build-absl/boundary_frontend_test")
set_tests_properties(boundary_frontend PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;155;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(link_distance_kernel_benchmark_smoke "/home/yjj/cgal_halfspace_project/build-absl/link_distance_kernel_benchmark" "/home/yjj/cgal_halfspace_project/resources/vamp/panda/panda_spherized.urdf" "/home/yjj/cgal_halfspace_project/data/realistic_sparse_camera.xyz" "0.02" "0.3" "7")
set_tests_properties(link_distance_kernel_benchmark_smoke PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;174;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(link_distance_frame_benchmark_smoke "/home/yjj/cgal_halfspace_project/build-absl/link_distance_frame_benchmark" "/home/yjj/cgal_halfspace_project/resources/vamp/panda/panda_spherized.urdf" "/home/yjj/cgal_halfspace_project/data/panda_complex_scene.xyz" "0.02" "2")
set_tests_properties(link_distance_frame_benchmark_smoke PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;183;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(point_cloud_input_fixtures "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/point_cloud_input_fixtures_test.py")
set_tests_properties(point_cloud_input_fixtures PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;191;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(link_distance_node_smoke "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/link_distance_node_test.py" "/home/yjj/cgal_halfspace_project/build-absl/link_distance_node" "/home/yjj/cgal_halfspace_project/tests/data/spherical_robot_test.urdf" "/home/yjj/cgal_halfspace_project/data/cube_points.xyz" "/home/yjj/cgal_halfspace_project/scripts/visualize_link_distances.py" "/home/yjj/cgal_halfspace_project/scripts/visualize_link_distances_3d.py" "/home/yjj/cgal_halfspace_project/scripts/validate_sphere_joint_frames.py")
set_tests_properties(link_distance_node_smoke PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;194;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(link_distance_stream "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/link_distance_stream_test.py" "/home/yjj/cgal_halfspace_project/build-absl/link_distance_node" "/home/yjj/cgal_halfspace_project/tests/data/spherical_robot_test.urdf" "/home/yjj/cgal_halfspace_project/data/cube_points.xyz")
set_tests_properties(link_distance_stream PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;203;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(link_distance_panda_001 "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/link_distance_panda_001_test.py" "/home/yjj/cgal_halfspace_project/build-absl/link_distance_node" "/home/yjj/cgal_halfspace_project/resources/vamp/panda/panda_spherized.urdf" "/home/yjj/cgal_halfspace_project/data/realistic_sparse_camera.xyz")
set_tests_properties(link_distance_panda_001 PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;209;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(panda_complex_scene "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/panda_complex_scene_test.py" "/home/yjj/cgal_halfspace_project/build-absl/link_distance_node" "/home/yjj/cgal_halfspace_project/resources/vamp/panda/panda_spherized.urdf" "/home/yjj/cgal_halfspace_project/data/panda_complex_scene.xyz")
set_tests_properties(panda_complex_scene PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;215;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(point_cloud_inputs "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/point_cloud_inputs_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(point_cloud_inputs PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;221;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_frontend_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_frontend_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(boundary_frontend_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;225;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(lse_kernel_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/lse_kernel_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(lse_kernel_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;229;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(execution_sharing_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/execution_sharing_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(execution_sharing_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;233;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(validation_acceleration_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/validation_acceleration_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(validation_acceleration_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;237;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(multi_frame_reuse_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/multi_frame_reuse_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(multi_frame_reuse_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;241;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(halfspace_batch_benchmark_smoke "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/halfspace_batch_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl/halfspace_batch_benchmark")
set_tests_properties(halfspace_batch_benchmark_smoke PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;245;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(smooth_distance_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/smooth_distance_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree")
set_tests_properties(smooth_distance_pipeline PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;249;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(smooth_distance_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/smooth_distance_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(smooth_distance_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;253;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_direct_query_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_direct_query_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(boundary_direct_query_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;257;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_direct_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_direct_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(boundary_direct_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;261;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_direct_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_direct_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree")
set_tests_properties(boundary_direct_pipeline PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;265;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_voxel_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_voxel_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(boundary_voxel_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;269;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_voxel_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_voxel_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree")
set_tests_properties(boundary_voxel_pipeline PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;273;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_local_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_local_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree")
set_tests_properties(boundary_local_pipeline PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;277;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_local_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_local_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(boundary_local_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;281;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_boundary_tree_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/octree_boundary_tree_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree")
set_tests_properties(octree_boundary_tree_pipeline PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;285;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(boundary_xyz_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/boundary_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(boundary_xyz_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;289;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_convex_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/octree_convex_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree")
set_tests_properties(octree_convex_pipeline PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;293;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(phase4_benchmark "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/phase4_benchmark_test.py" "/home/yjj/cgal_halfspace_project/build-absl")
set_tests_properties(phase4_benchmark PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;297;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/octree_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree")
set_tests_properties(octree_pipeline PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;301;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(octree_boundary_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/octree_boundary_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree")
set_tests_properties(octree_boundary_pipeline PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;305;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
add_test(voxel_pipeline "/usr/bin/python3.10" "/home/yjj/cgal_halfspace_project/tests/voxel_pipeline_test.py" "/home/yjj/cgal_halfspace_project/build-absl/build_halfspace_tree" "/home/yjj/cgal_halfspace_project/build-absl/alpha_wrap_test" "/home/yjj/cgal_halfspace_project/tests/data/voxel_containment.xyz")
set_tests_properties(voxel_pipeline PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/yjj/cgal_halfspace_project/CMakeLists.txt;309;add_test;/home/yjj/cgal_halfspace_project/CMakeLists.txt;0;")
